### ISSUE TITLE
Don't pin readline?

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/mdsplus-feedstock#11]
Is it possible to not pin readline? (Newer pythons use readline 8)

**Comment by smithsp** [comment]
Thank you for asking.  I don't think that we needed any particular version of readline that I remember, but we just pinned the build and run requirements together.  The recipe could probably use some modernization work.  Let me know of the urgency, as it is pretty low priority for me.

**Comment by CJ-Wright** [comment]
It isn't particularly urgent, it might become harder and harder to install though, as things it is installed on need more modern requirements.

**Comment by smithsp** [comment]
It is no longer pinned.
